# Generated by Django 5.1.4 on 2024-12-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
